#include <stdio.h>

#include "parser.h"
#include "front.h"

static void error();

/**
 * Tlris is the example Recursive-Descent Parser in pp. 181 - 185 in the 
 * textbook 
 *
 * Sebesta, R. W. (2012). Concepts of Programming Languages. 
 * Pearson, 10th edition.
 *
 *
 * */

/* P
 * Parses strings in the language generated by the rule:
 * P ::= S
 */
void P()
{
    printf("Enter <prog>\n");

    /* Parse the statement */
    S();

    printf("Exit <prog>\n");
} /* End of function P */

/* S
 * Parses strings in the language generated by the rule:
 * S ::= V := E Slr | cin >> V Slr | cout << E Slr | ++V Slr | --V Slr | for V in E .. E : S Slr | if C : S M Spd
 */
void S()
{
    printf("Enter <stmt>\n");



    printf("Exit <stmt>\n");
} /* End of function S */

/* Spd
 * Parses strings in the language generated by the rule:
 * Spd ::= Slr | else : S Slr
 */
void Spd()
{
    printf("Enter <stmt_pd_helper>\n");



    printf("Exit <stmt_pd_helper>\n");
} /* End of function Spd */

/* Slr
 * Parses strings in the language generated by the rule:
 * Slr ::= ; S Slr | ε
 */
void Slr()
{
    printf("Enter <stmt_lr_helper>\n");



    printf("Exit <stmt_lr_helper>\n");
} /* End of function Slr */

/* M
 * Parses strings in the language generated by the rule:
 * M ::= elif C : S M | ε
 * */
void M()
{
    printf("Enter <more>\n");



    printf("Exit <more>\n");
} /* End of function M */

/* C
 * Parses strings in the language generated by the rule:
 * C ::= A Clr
 * */
void C()
{
    printf("Enter <comp_or>\n");



    printf("Exit <comp_or>\n");
} /* End of function C */

/* Clr
 * Parses strings in the language generated by the rule:
 * Clr ::= or A Clr | ε
 * */
void Clr()
{
    printf("Enter <comp_or_lr_helper>\n");



    printf("Exit <comp_or_lr_helper>\n");
} /* End of function Clr */

/* A
 * Parses strings in the language generated by the rule:
 * A ::= R Alr
 * */
void A()
{
    printf("Enter <and_comp>\n");



    printf("Exit <and_comp>\n");
} /* End of function A */

/* Alr
 * Parses strings in the language generated by the rule:
 * Alr ::= and R Alr | ε
 * */
void Alr()
{
    printf("Enter <and_comp_lr_helper>\n");



    printf("Exit <and_comp_lr_helper>\n");
} /* End of function Alr */

/* R
 * Parses strings in the language generated by the rule:
 * R ::= not R | E Rpd
 * */
void R()
{
    printf("Enter <relation>\n");



    printf("Exit <relation>\n");
} /* End of function R */

/* Rpd
 * Parses strings in the language generated by the rule:
 * Rpd ::= < E | > E | == E | <> E | <= E | >= E
 * */
void Rpd()
{
    printf("Enter <relation_pd_helper>\n");



    printf("Exit <relation_pd_helper>\n");
} /* End of function Rpd */

/* E
 * Parses strings in the language generated by the rule:
 * E ::= T Elr
 * */
void E()
{
    printf("Enter <expr>\n");

    /* Parse the first term */
    T();

    /* As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == ADD_OP || nextToken == SUB_OP) {
        lex();
        term();
    }

    printf("Exit <expr>\n");
} /* End of function E */

/* Elr
 * Parses strings in the language generated by the rule:
 * Elr ::= + T Elr | - T Elr | ε
 * */
void Elr()
{
    printf("Enter <expr_lr_helper>\n");

    /* Parse the first term */
    T();

    printf("Exit <expr_lr_helper>\n");
} /* End of function Elr */

/* T
 * Parses strings in the language generated by the rule:
 * T ::= F Tlr
 * */
void T()
{
    printf("Enter <term>\n");

    /* Parse the first factor */
    F();

    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP) {
        lex();
        factor();
    }

    printf("Exit <term>\n");
} /* End of function T */

/* Tlr
 * Parses strings in the language generated by the rule:
 * Tlr ::= * F Tlr | / F Tlr | % F Tlr | ε
 * */
void Tlr()
{
    printf("Enter <term_lr_helper>\n");



    printf("Exit <term_lr_helper>\n");
} /* End of function Elr */

/* F
 * Parses strings in the language generated by the rule:
 * F ::= (E) | I | L | V | ++V | --V
 * */
void F()
{
    printf("Enter <factor>\n");

    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LITERAL) {
        lex(); /* Get the next token */
    } else {
        /* If the RHS is (<expr>), call lex to pass over the 
        left parenthesis, call expr, and check for the right 
        parenthesis */
        if (nextToken == LEFT_PAREN) {
            lex(); 
            expr();

            if (nextToken == RIGHT_PAREN) {
                lex(); 
            } else { 
                error();
            }
        } /* End of if (nextToken == ... */
        /* It was not an id, an integer literal, or a left parenthesis */
        else 
        { 
            error(); 
        }
    } /* End of else */

    printf("Exit <factor>\n");;
} /* End of function F */

/* V
 * Parses strings in the language generated by the rule:
 * V ::= H X | _X
 * */
void V()
{
    printf("Enter <var>\n");



    printf("Exit <var>\n");
} /* End of function V */

/* H
 * Parses strings in the language generated by the rule:
 * H ::= a | b | c | ... | x | y | z
 * */
void H()
{
    printf("Enter <h_alpha>\n");



    printf("Exit <h_alpha>\n");
} /* End of function H */

/* I
 * Parses strings in the language generated by the rule:
 * I ::= D Ipd
 * */
void I()
{
    printf("Enter <int>\n");



    printf("Exit <int>\n");
} /* End of function I */

/* Ipd
 * Parses strings in the language generated by the rule:
 * Ipd ::= I | ε
 * */
void Ipd()
{
    printf("Enter <int>\n");



    printf("Exit <int>\n");
} /* End of function Ipd */

/* L
 * Parses strings in the language generated by the rule:
 * L ::= . I | I . I
 * */
void L()
{
    printf("Enter <float>\n");



    printf("Exit <float>\n");
} /* End of function L */

/* D
 * Parses strings in the language generated by the rule:
 * D ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
 * */
void D()
{
    printf("Enter <digit>\n");



    printf("Exit <digit>\n");
} /* End of function D */

static void error() 
{
    printf("Error (more is desired, but not implemented).\n");
}
