#include <stdio.h>

#include "parser.h"
#include "front.h"

static void error();

/**
 * Tlris is the example Recursive-Descent Parser in pp. 181 - 185 in the 
 * textbook 
 *
 * Sebesta, R. W. (2012). Concepts of Programming Languages. 
 * Pearson, 10th edition.
 *
 *
 * */

/* P
 * Parses strings in the language generated by the rule:
 * P ::= S
 */
void P()
{
    printf("Enter <prog>\n");

    /* Parse the statement */
    S();

    printf("Exit <prog>\n");
} /* End of function P */

/* S
 * Parses strings in the language generated by the rule:
 * S ::= V := E Slr | cin >> V Slr | cout << E Slr | ++V Slr | --V Slr | for V in E .. E : S Slr | if C : S M Spd Slr
 */
void S()
{
    printf("Enter <stmt>\n");

    switch (nextToken) {
        // S ::= V := E Slr
        case IDENT:
            V();

            if (nextToken == ASSIGNMENT_OP) { // Consumes ASSIGNMENT_OP
                lex();
                E();
            }
            else
                error();
            
            break;

        // S ::= cin >> V Slr
        case KEY_CIN:
            lex();
            if (nextToken == SHIFT_R_OP) { // Consumes SHIFT_R_OP
                lex();
                V();
            }
            else error();

            break;

        // S ::= cout << E Slr
        case KEY_COUT:
            lex();
            if (nextToken == SHIFT_L_OP) { // Consumes SHIFT_L_OP
                lex();
                E();
            }
            else
                error();

            break;

        // S ::= ++V Slr
        case INC_OP:
            lex();
            V();
            break;

        // S ::= --V Slr
        case DEC_OP:
            lex();
            V();
            break;

        // S ::= for V in E .. E : S Slr
        case KEY_FOR:
            lex();
            V();

            lex();
            if (nextToken == KEY_IN) { // Consumes KEY_IN
                lex();
                E();

                lex();
                if (nextToken == RANGE_OP) { // Consumes RANGE_OP
                    lex();
                    E();

                    lex();
                    if (nextToken == COLON) { // Consumes COLON
                        lex();
                        S();
                    }
                    else
                        error();
                }
                else error();
            }
            else error();

            break;
        
        // S ::= if C : S M Spd Slr
        case KEY_IF:
            lex();
            C();

            if (nextToken == COLON) { // Consumes COLON
                lex();
                S();

                M();

                Spd();
            }
            else error();

            break;
        
        default:
            error();
    }

    Slr();

    printf("Exit <stmt>\n");
} /* End of function S */

/* Spd
 * Parses strings in the language generated by the rule:
 * Spd ::= else : S | ε
 */
void Spd()
{
    printf("Enter <stmt_pd_helper>\n");

    if (nextToken == KEY_ELSE) { // Consumes KEY_ELSE
        lex();
        if (nextToken == COLON) { // Consumes COLON
            lex();
            S();
        }
        else error();
    }

    printf("Exit <stmt_pd_helper>\n");
} /* End of function Spd */

/* Slr
 * Parses strings in the language generated by the rule:
 * Slr ::= ; S Slr | ε
 */
void Slr()
{
    printf("Enter <stmt_lr_helper>\n");

    if (nextToken == SEMICOLON) { // Consumes SEMICOLON
        lex();
        S();

        lex();
        Slr();
    }

    printf("Exit <stmt_lr_helper>\n");
} /* End of function Slr */

/* M
 * Parses strings in the language generated by the rule:
 * M ::= elif C : S M | ε
 * */
void M()
{
    printf("Enter <more_elif>\n");

    if (nextToken == KEY_ELIF) { // Consumes KEY_ELIF
        lex();
        C();

        if (nextToken == COLON) { // Consumes COLON
            lex();
            S();

            M();
        }
        else error();
    }

    printf("Exit <more_elif>\n");
} /* End of function M */

/* C
 * Parses strings in the language generated by the rule:
 * C ::= A Clr
 * */
void C()
{
    printf("Enter <comp_or>\n");

    A();

    Clr();

    printf("Exit <comp_or>\n");
} /* End of function C */

/* Clr
 * Parses strings in the language generated by the rule:
 * Clr ::= or A Clr | ε
 * */
void Clr()
{
    printf("Enter <comp_or_lr_helper>\n");

    if (nextToken == BOOLEAN_OR) { // Consumes BOOLEAN_OR
        lex();
        A();

        Clr();
    }

    printf("Exit <comp_or_lr_helper>\n");
} /* End of function Clr */

/* A
 * Parses strings in the language generated by the rule:
 * A ::= R Alr
 * */
void A()
{
    printf("Enter <and_comp>\n");

    R();

    Alr();

    printf("Exit <and_comp>\n");
} /* End of function A */

/* Alr
 * Parses strings in the language generated by the rule:
 * Alr ::= and R Alr | ε
 * */
void Alr()
{
    printf("Enter <and_comp_lr_helper>\n");

    if (nextToken == BOOLEAN_AND) { // Consumes BOOLEAN_AND
        lex();
        R();

        Alr();
    }

    printf("Exit <and_comp_lr_helper>\n");
} /* End of function Alr */

/* R
 * Parses strings in the language generated by the rule:
 * R ::= not R | E Rpd
 * */
void R()
{
    printf("Enter <relation>\n");

    if (nextToken == BOOLEAN_NOT) {// Consumes BOOLEAN_NOT
        lex();
        R();
    }
    else {
        E();

        Rpd();
    }

    printf("Exit <relation>\n");
} /* End of function R */

/* Rpd
 * Parses strings in the language generated by the rule:
 * Rpd ::= < E | > E | == E | <> E | <= E | >= E
 * */
void Rpd()
{
    printf("Enter <relation_pd_helper>\n");

    if (nextToken == LESSER_OP
        || nextToken == GREATER_OP
        || nextToken == EQUAL_OP
        || nextToken == NEQUAL_OP
        || nextToken == LEQUAL_OP
        || nextToken == GEQUAL_OP) {
        lex();
        E();
    }
    else
        error();

    printf("Exit <relation_pd_helper>\n");
} /* End of function Rpd */

/* E
 * Parses strings in the language generated by the rule:
 * E ::= T Elr
 * */
void E()
{
    printf("Enter <expr>\n");

    /* Parse the first term */
    T();

    /* Enter helper function */
    Elr();

    printf("Exit <expr>\n");
} /* End of function E */

/* Elr
 * Parses strings in the language generated by the rule:
 * Elr ::= + T Elr | - T Elr | ε
 * */
void Elr()
{
    printf("Enter <expr_lr_helper>\n");

    /* As long as the next token is + or -, get
    the next token and parse the next term */
    if (nextToken == ADD_OP || nextToken == SUB_OP) {
        lex();
        T();

        Elr();
    }

    printf("Exit <expr_lr_helper>\n");
} /* End of function Elr */

/* T
 * Parses strings in the language generated by the rule:
 * T ::= F Tlr
 * */
void T()
{
    printf("Enter <term>\n");

    /* Parse the first factor */
    F();

    /* Enter helper function */
    Tlr();

    printf("Exit <term>\n");
} /* End of function T */

/* Tlr
 * Parses strings in the language generated by the rule:
 * Tlr ::= * F Tlr | / F Tlr | % F Tlr | ε
 * */
void Tlr()
{
    printf("Enter <term_lr_helper>\n");

    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    if (nextToken == MULT_OP || nextToken == DIV_OP || nextToken == MOD_OP) {
        lex();
        F();

        Tlr();
    }

    printf("Exit <term_lr_helper>\n");
} /* End of function Elr */

/* F
 * Parses strings in the language generated by the rule:
 * F ::= (E) | I | L | V | ++V | --V
 * */
void F()
{
    printf("Enter <factor>\n");

    switch (nextToken) {
        case RIGHT_PAREN:
            lex();
            E();

            lex();
            if (nextToken != LEFT_PAREN)
                error();

            break;
        
        case INT_LITERAL:
            I();
            break;
        
        case FLOAT_LITERAL:
            L();
            break;

        case IDENT:
            V();
            break;

        case INC_OP:
        case DEC_OP:
            lex();
            V();
            break;

        default:
            error();
    }

    // /* Determine which RHS */
    // if (nextToken == IDENT || nextToken == INT_LITERAL) {
    //     lex(); /* Get the next token */
    // } else {
    //     /* If the RHS is (<expr>), call lex to pass over the 
    //     left parenthesis, call expr, and check for the right 
    //     parenthesis */
    //     if (nextToken == LEFT_PAREN) {
    //         lex(); 
    //         E();

    //         if (nextToken == RIGHT_PAREN) {
    //             lex(); 
    //         } else { 
    //             error();
    //         }
    //     } /* End of if (nextToken == ... */
    //     /* It was not an id, an integer literal, or a left parenthesis */
    //     else 
    //     { 
    //         error(); 
    //     }
    // } /* End of else */

    printf("Exit <factor>\n");
} /* End of function F */

/* V
 * Parses strings in the language generated by the rule:
 * V ::= H X | _X
 * */
void V()
{
    printf("Enter <var_start>\n");

    lex();

    printf("Exit <var_start>\n");
} /* End of function V */

/* X
 * Parses strings in the language generated by the rule:
 * X ::= H X | D X | _X | ε
 * */
void X()
{
    printf("Enter <x_var>\n");



    printf("Exit <x_var>\n");
} /* End of function X */

/* H
 * Parses strings in the language generated by the rule:
 * H ::= a | b | c | ... | x | y | z
 * */
void H()
{
    printf("Enter <h_alpha>\n");



    printf("Exit <h_alpha>\n");
} /* End of function H */

/* I
 * Parses strings in the language generated by the rule:
 * I ::= D Ipd
 * */
void I()
{
    printf("Enter <int>\n");

    D();

    Ipd();

    printf("Exit <int>\n");
} /* End of function I */

/* Ipd
 * Parses strings in the language generated by the rule:
 * Ipd ::= I | ε
 * */
void Ipd()
{
    printf("Enter <int_pd_helper>\n");

    lex();

    printf("Exit <int_pd_helper>\n");
} /* End of function Ipd */

/* L
 * Parses strings in the language generated by the rule:
 * L ::= . I | I . I
 * */
void L()
{
    printf("Enter <float>\n");

    lex();

    printf("Exit <float>\n");
} /* End of function L */

/* D
 * Parses strings in the language generated by the rule:
 * D ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
 * */
void D()
{
    printf("Enter <digit>\n");



    printf("Exit <digit>\n");
} /* End of function D */

static void error() 
{
    printf("Error (more is desired, but not implemented).\n");
}
